const CONFIG = {
  maxArticlesPerSource: 10,
  maxRenderedArticles: 60,
  requestTimeoutMs: 9000,
  useBackend: true,
  useLiveFeeds: true,
  api: {
    // Change this one value if your deployed backend uses another route.
    // Prefer a relative path when frontend and backend share a domain.
    baseUrl: window.CYBERINTEL_CONFIG?.apiBaseUrl || "",
    newsEndpoint: window.CYBERINTEL_CONFIG?.newsEndpoint || "/api/news"
  },
  sources: [
    {id:"thehackernews",name:"The Hacker News",feed:"https://feeds.feedburner.com/TheHackersNews",homepage:"https://thehackernews.com/",description:"Cybersecurity news, vulnerabilities, threat research and enterprise security."},
    {id:"bleepingcomputer",name:"BleepingComputer",feed:"https://www.bleepingcomputer.com/feed/",homepage:"https://www.bleepingcomputer.com/",description:"Security news covering malware, ransomware, Windows and cybercrime."},
    {id:"krebsonsecurity",name:"Krebs on Security",feed:"https://krebsonsecurity.com/feed/",homepage:"https://krebsonsecurity.com/",description:"Investigative reporting and analysis on cybercrime and security."},
    {id:"securityweek",name:"SecurityWeek",feed:"https://feeds.feedburner.com/securityweek",homepage:"https://www.securityweek.com/",description:"Enterprise security news, vulnerability research and threat intelligence."}
  ]
};

function loadBookmarks(){
  try{
    const value=JSON.parse(localStorage.getItem("cyberintel.bookmarks")||"[]");
    return new Set(Array.isArray(value)?value.filter(v=>typeof v==="string"):[]);
  }catch{
    localStorage.removeItem("cyberintel.bookmarks");
    return new Set();
  }
}
const state={allArticles:[],filteredArticles:[],mode:"offline",loading:false,bookmarks:loadBookmarks()};
const $=s=>document.querySelector(s);
const els={
  sidebar:$("#sidebar"),mobileBackdrop:$("#mobileBackdrop"),mobileMenu:$("#mobileMenu"),sidebarToggle:$("#sidebarToggle"),
  pageTitle:$("#pageTitle"),search:$("#searchInput"),feedSearch:$("#feedSearch"),refresh:$("#refreshBtn"),dashboardRefresh:$("#dashboardRefresh"),
  feedStatus:$("#feedStatus"),sideFeedStatus:$("#sideFeedStatus"),sideLastUpdated:$("#sideLastUpdated"),settingsMode:$("#settingsMode"),footerMode:$("#footerMode"),
  metricGrid:$("#metricGrid"),dashboardNews:$("#dashboardNews"),priorityList:$("#priorityList"),topicList:$("#topicList"),sourceMiniList:$("#sourceMiniList"),
  category:$("#categoryFilter"),source:$("#sourceFilter"),sort:$("#sortFilter"),newsGrid:$("#newsGrid"),resultCount:$("#resultCount"),activeFilters:$("#activeFilters"),
  statePanel:$("#statePanel"),stateTitle:$("#stateTitle"),stateMessage:$("#stateMessage"),stateAction:$("#stateAction"),
  threatCategories:$("#threatCategories"),threatActivity:$("#threatActivity"),vulnerabilityTable:$("#vulnerabilityTable"),
  bookmarkGrid:$("#bookmarkGrid"),bookmarkEmpty:$("#bookmarkEmpty"),sourceCards:$("#sourceCards"),clearBookmarks:$("#clearBookmarks")
};

function escapeHtml(value=""){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function cleanText(value=""){const t=document.createElement("textarea");t.innerHTML=String(value);return t.value.replace(/\s+/g," ").trim()}
function validHttpUrl(value){try{const u=new URL(value,location.href);return ["http:","https:"].includes(u.protocol)?u.href:"#"}catch{return "#"}}
function classifyArticle(title,summary=""){const text=`${title} ${summary}`.toLowerCase();const rules=[["Ransomware",/ransom|extortion|encrypt/],["Malware",/malware|trojan|stealer|botnet|spyware|backdoor/],["Vulnerabilities",/cve-|vulnerability|vulnerable|zero-day|exploit/],["Data Breaches",/breach|leak|exposed data|stolen data/],["Cloud Security",/cloud|aws|azure|gcp|kubernetes|container/],["AI Security",/\bai\b|artificial intelligence|llm|agent|prompt injection/],["Cyber Attacks",/attack|campaign|intrusion|phishing|ddos|compromise/],["Threat Intelligence",/threat actor|apt|threat intel|ioc|indicator/]];return rules.find(([,r])=>r.test(text))?.[0]||"General Cybersecurity"}
function makeTags(title,summary){const text=`${title} ${summary}`.toLowerCase();const candidates=[["CVE",/cve[-\s]?\d{4}/],["Ransomware",/ransom/],["Malware",/malware|trojan|stealer/],["Phishing",/phishing/],["Cloud",/cloud|aws|azure|gcp/],["AI Security",/\bai\b|llm|agent/],["Data Breach",/breach|leak/],["Zero-Day",/zero[- ]day/],["Supply Chain",/supply chain/],["Vulnerability",/vulnerability|exploit/],["Identity",/identity|credential|account/]];const tags=candidates.filter(([,r])=>r.test(text)).map(([n])=>n).slice(0,4);return tags.length?tags:["Cybersecurity"]}
function normalizeArticle(item,source){const title=cleanText(item.title||"Untitled security story");const summary=cleanText(item.description||item.content||item.summary||"No summary available.");return{id:item.id||`${source.id}-${btoa(unescape(encodeURIComponent(title))).slice(0,18)}`,source:source.name,sourceId:source.id,title,summary,url:validHttpUrl(item.link||source.homepage),publishedAt:item.publishedAt||item.pubDate||item.isoDate||item.published||new Date().toISOString(),category:item.category||classifyArticle(title,summary),tags:Array.isArray(item.tags)?item.tags.slice(0,4):makeTags(title,summary),image:item.image||item.thumbnail||item.enclosure?.link||"",severity:item.severity||"",isNew:item.isNew===true}}
function formatDate(date){const d=new Date(date);if(Number.isNaN(d.getTime()))return"Unknown";return new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
function relativeDate(date){const d=new Date(date),diff=Date.now()-d.getTime();if(Number.isNaN(d.getTime()))return"";const m=Math.floor(diff/60000);if(m>=0&&m<60)return`${Math.max(1,m)}m ago`;const h=Math.floor(m/60);if(h>=0&&h<24)return`${h}h ago`;return formatDate(date)}
function imageFallback(source,index=0){const letters=(source||"CI").replace(/[^A-Za-z]/g,"").slice(0,3).toUpperCase();const sv=`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="520"><rect width="100%" height="100%" fill="#111821"/><path d="M0 410L260 250l150 100 190-170 300 210V520H0z" fill="#151e28"/><text x="52" y="82" fill="#45d6a2" font-family="monospace" font-size="30" font-weight="600">${letters}</text></svg>`;return`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(sv)}`}
function severity(article){if(article?.severity)return article.severity;const t=`${article.title} ${article.summary} ${(article.tags||[]).join(" ")}`.toLowerCase();if(/critical|actively exploited|zero-day|ransomware|remote code execution|rce/.test(t))return"Critical";if(/vulnerability|exploit|breach|malware|attack|phishing/.test(t))return"High";if(/threat|credential|identity|campaign|intrusion/.test(t))return"Medium";return"Low"}
function dedupeArticles(articles){const seen=new Set();return articles.filter(a=>{const key=a.url&&a.url!=="#"?a.url:`${a.source}-${a.title}`;if(seen.has(key))return false;seen.add(key);return true})}
async function fetchJson(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),CONFIG.requestTimeoutMs);try{const r=await fetch(url,{signal:controller.signal,headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
async function fetchBackend(force=false){const base=`${CONFIG.api.baseUrl}${CONFIG.api.newsEndpoint}`;const url=force?`${base}${base.includes("?")?"&":"?"}refresh=1`:base;const data=await fetchJson(url);const items=Array.isArray(data)?data:(data.articles||data.items||data.news);if(!Array.isArray(items))throw new Error("Unsupported API response");const sourceByName=new Map(CONFIG.sources.map(s=>[s.name,s]));return dedupeArticles(items.map((item,i)=>{const source=sourceByName.get(item.source)||CONFIG.sources.find(s=>s.id===item.sourceId)||{id:`api-${i}`,name:item.source||"CyberIntel API",homepage:item.url||"#",description:"Backend intelligence source"};return normalizeArticle({...item,link:item.url||item.link},source)}))}
function showState(type,title,message,action="Retry"){els.statePanel.hidden=false;els.statePanel.dataset.type=type;els.stateTitle.textContent=title;els.stateMessage.textContent=message;els.stateAction.textContent=action}
function hideState(){els.statePanel.hidden=true}
function showSkeletons(){hideState();els.newsGrid.innerHTML=Array.from({length:6},()=>'<div class="skeleton" aria-hidden="true"></div>').join("")}
async function loadNews(force=false){if(state.loading)return;state.loading=true;els.refresh.classList.add("spinning");showSkeletons();try{const articles=await fetchBackend(force);if(!articles.length)throw new Error("The backend returned no articles");state.mode="live";state.allArticles=articles;setMode("live")}catch(e){state.mode="offline";state.allArticles=[];setMode("offline");showState("error","Live intelligence unavailable","CyberIntel could not reach its backend or retrieve current news. Check the server and Supabase connection.","Retry")}finally{state.loading=false;els.refresh.classList.remove("spinning");populateFilters();renderAll()}}
function setMode(mode){const label=mode==="live"?"LIVE API":"OFFLINE";els.feedStatus.textContent=label;els.sideFeedStatus.textContent=label;els.settingsMode.textContent=label;els.sideLastUpdated.textContent=relativeDate(new Date());els.footerMode.textContent=mode==="live"?"Backend API connected • normalized intelligence":"Backend unavailable • no live intelligence"}
function populateFilters(){const cats=[...new Set(state.allArticles.map(a=>a.category))].sort(),sources=[...new Set(state.allArticles.map(a=>a.source))].sort(),oc=els.category.value,os=els.source.value;els.category.innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join("");els.source.innerHTML='<option value="all">All sources</option>'+sources.map(s=>`<option value="${escapeHtml(s)}">${escapeHtml(s)}</option>`).join("");if(cats.includes(oc))els.category.value=oc;if(sources.includes(os))els.source.value=os}
function getFiltered(){const q=`${els.search.value} ${els.feedSearch.value}`.trim().toLowerCase(),cat=els.category.value,src=els.source.value,sort=els.sort.value;let a=state.allArticles.filter(x=>{const hay=`${x.title} ${x.summary} ${x.source} ${x.category} ${x.tags.join(" ")}`.toLowerCase();return(!q||hay.includes(q))&&(cat==="all"||x.category===cat)&&(src==="all"||x.source===src)});a.sort((x,y)=>{const d=new Date(x.publishedAt)-new Date(y.publishedAt);return sort==="newest"?-d:d});return a.slice(0,CONFIG.maxRenderedArticles)}
function renderAll(){state.filteredArticles=getFiltered();renderDashboard();renderNews();renderThreats();renderVulnerabilities();renderBookmarks();renderSources();renderActiveFilters()}
function metric(label,value,note,icon){return`<div class="metric"><div class="metric-top"><span>${label}</span><span class="metric-icon">${icon}</span></div><strong>${value}</strong><small>${note}</small></div>`}
function renderDashboard(){const a=state.allArticles,counts={};a.forEach(x=>counts[x.category]=(counts[x.category]||0)+1);const critical=a.filter(x=>severity(x)==="Critical").length,news=a.filter(x=>x.isNew===true||Date.now()-new Date(x.publishedAt).getTime()<86400000).length;els.metricGrid.innerHTML=[metric("Total articles",a.length,"Current intelligence set","◉"),metric("New",news,"Last 24 hours","↗"),metric("Critical",critical,"Priority signals","!"),metric("Ransomware",counts["Ransomware"]||0,"Current coverage","▣"),metric("Malware",counts["Malware"]||0,"Current coverage","◆"),metric("Sources",new Set(a.map(x=>x.source)).size,"Active inputs","▤")].join("");const latest=[...a].sort((x,y)=>new Date(y.publishedAt)-new Date(x.publishedAt)).slice(0,6);els.dashboardNews.innerHTML=latest.map(compactStory).join("")||emptyInline("No intelligence available.");const priorities=[...a].sort((x,y)=>({Critical:0,High:1,Medium:2,Low:3}[severity(x)]-({Critical:0,High:1,Medium:2,Low:3}[severity(y)]))).slice(0,4);els.priorityList.innerHTML=priorities.map(x=>`<div class="priority-item ${severity(x).toLowerCase()}"><span class="priority-bar"></span><div><h3>${escapeHtml(x.title)}</h3><small>${severity(x)} · ${escapeHtml(relativeDate(x.publishedAt))}</small></div></div>`).join("")||emptyInline("No priority signals.");const topics=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,6);els.topicList.innerHTML=topics.map(([n,c])=>`<button class="topic" type="button" data-topic="${escapeHtml(n)}"><b>${escapeHtml(n)}</b><span>${c} ${c===1?"story":"stories"}</span></button>`).join("");els.topicList.querySelectorAll("[data-topic]").forEach(b=>b.onclick=()=>{els.category.value=b.dataset.topic;showSection("latest")});els.sourceMiniList.innerHTML=CONFIG.sources.map(s=>`<div class="source-mini"><b>${escapeHtml(s.name)}</b><span>${a.filter(x=>x.sourceId===s.id||x.source===s.name).length} stories</span></div>`).join("")}
function compactStory(x){return`<a class="compact-story" href="${escapeHtml(validHttpUrl(x.url))}" target="_blank" rel="noopener noreferrer"><img class="compact-thumb" src="${escapeHtml(x.image||imageFallback(x.source))}" alt="" loading="lazy"><div><span class="compact-source">${escapeHtml(x.source)}</span><h3>${escapeHtml(x.title)}</h3></div><span class="compact-time">${escapeHtml(relativeDate(x.publishedAt))}</span></a>`}
function emptyInline(text){return`<div style="padding:18px;color:var(--muted);font-size:10px">${escapeHtml(text)}</div>`}
function renderNews(){const a=state.filteredArticles;els.resultCount.textContent=`${a.length} ${a.length===1?"story":"stories"}`;if(!a.length){els.newsGrid.innerHTML="";showState("empty","No matching intelligence","Try a different search term, category or source.");return}hideState();els.newsGrid.innerHTML=a.map(newsCard).join("");bindCardActions()}
function newsCard(x){const sev=severity(x),saved=state.bookmarks.has(x.id);return`<article class="news-card"><img class="news-thumb" src="${escapeHtml(x.image||imageFallback(x.source))}" alt="" loading="lazy" onerror="this.src='${imageFallback(x.source)}'"><div class="news-body"><div class="news-meta"><span class="news-source">${escapeHtml(x.source)}</span><span>${escapeHtml(relativeDate(x.publishedAt))}</span></div><div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><span class="category-badge">${escapeHtml(x.category)}</span><span class="severity ${sev.toLowerCase()}">${sev}</span></div><h3>${escapeHtml(x.title)}</h3><p class="news-summary">${escapeHtml(x.summary)}</p><div class="tags">${x.tags.map(t=>`<span class="tag">#${escapeHtml(t)}</span>`).join("")}</div><div class="news-footer"><span style="color:var(--muted-2);font-size:8px" title="${escapeHtml(formatDate(x.publishedAt))}">${escapeHtml(formatDate(x.publishedAt))}</span><span style="display:flex;align-items:center;gap:9px"><button class="bookmark ${saved?"saved":""}" type="button" data-bookmark="${escapeHtml(x.id)}" aria-label="${saved?"Remove":"Save"} bookmark">${saved?"★":"☆"}</button><a href="${escapeHtml(validHttpUrl(x.url))}" target="_blank" rel="noopener noreferrer">Read ↗</a></span></div></div></article>`}
function bindCardActions(){els.newsGrid.querySelectorAll("[data-bookmark]").forEach(b=>b.onclick=()=>toggleBookmark(b.dataset.bookmark))}
function toggleBookmark(id){if(state.bookmarks.has(id))state.bookmarks.delete(id);else state.bookmarks.add(id);try{localStorage.setItem("cyberintel.bookmarks",JSON.stringify([...state.bookmarks]))}catch{ /* storage unavailable; keep bookmark state for this session */ };renderAll()}
function renderActiveFilters(){const filters=[];const q=els.search.value.trim()||els.feedSearch.value.trim();if(q)filters.push(["Search",q,()=>{els.search.value="";els.feedSearch.value="";renderAll()}]);if(els.category.value!=="all")filters.push(["Category",els.category.value,()=>{els.category.value="all";renderAll()}]);if(els.source.value!=="all")filters.push(["Source",els.source.value,()=>{els.source.value="all";renderAll()}]);els.activeFilters.hidden=!filters.length;els.activeFilters.innerHTML=filters.map(([t,v],i)=>`<button type="button" data-filter="${i}">${escapeHtml(t)}: ${escapeHtml(v)} ×</button>`).join("");els.activeFilters.querySelectorAll("[data-filter]").forEach(b=>b.onclick=filters[Number(b.dataset.filter)][2])}
function renderThreats(){const counts={};state.allArticles.forEach(x=>counts[x.category]=(counts[x.category]||0)+1);els.threatCategories.innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([n,c])=>`<div class="signal-row"><b>${escapeHtml(n)}</b><span>${c} stories</span><span>${c>=3?"Active":"Observed"}</span></div>`).join("")||emptyInline("No threat data.");els.threatActivity.innerHTML=state.allArticles.filter(x=>["Threat Intelligence","Ransomware","Malware","Cyber Attacks"].includes(x.category)).sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)).slice(0,6).map(compactStory).join("")||emptyInline("No threat activity identified.")}
function renderVulnerabilities(){const a=state.allArticles.filter(x=>x.category==="Vulnerabilities"||x.tags.some(t=>/CVE|Vulnerability|Zero-Day/i.test(t)));els.vulnerabilityTable.innerHTML=`<div class="vuln-row head"><span>CVE / Signal</span><span>Finding</span><span>Severity</span><span>Published</span><span>Status</span></div>`+(a.length?a.slice(0,20).map(x=>`<div class="vuln-row"><code>${escapeHtml((x.tags.find(t=>/CVE/i.test(t))||"VULN").toUpperCase())}</code><b>${escapeHtml(x.title)}</b><span><span class="severity ${severity(x).toLowerCase()}">${severity(x)}</span></span><span>${escapeHtml(formatDate(x.publishedAt).split(",")[0])}</span><span>${severity(x)==="Critical"?"Prioritize":"Review"}</span></div>`).join(""):emptyInline("No vulnerability-focused stories are currently available."))}
function renderBookmarks(){const a=state.allArticles.filter(x=>state.bookmarks.has(x.id));els.bookmarkGrid.innerHTML=a.map(newsCard).join("");els.bookmarkEmpty.hidden=!!a.length;bindCardActions()}
function renderSources(){els.sourceCards.innerHTML=CONFIG.sources.map(s=>`<a class="source-card" href="${escapeHtml(validHttpUrl(s.homepage))}" target="_blank" rel="noopener noreferrer"><b>${escapeHtml(s.name)}</b><span>${escapeHtml(s.id.toUpperCase())}</span><p>${escapeHtml(s.description)}</p><span class="source-status">Configured input</span></a>`).join("")}
function showSection(id){const target=$( "#"+id)||$("#dashboard");document.querySelectorAll(".page-section").forEach(s=>s.classList.remove("active-section"));target.classList.add("active-section");document.querySelectorAll(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.section===id));els.pageTitle.textContent=target.querySelector("h1")?.textContent||"Dashboard";window.scrollTo({top:0,behavior:"smooth"});closeMobileNav()}
function route(){const hash=location.hash.replace("#","")||"dashboard";const section=$( "#"+hash);showSection(section&&section.classList.contains("page-section")?hash:"dashboard")}
function closeMobileNav(){els.sidebar.classList.remove("mobile-open");els.mobileBackdrop.hidden=true}
function bindEvents(){window.addEventListener("hashchange",route);els.refresh.onclick=()=>loadNews(true);els.dashboardRefresh.onclick=()=>loadNews(true);els.stateAction.onclick=()=>loadNews(true);els.search.oninput=renderAll;els.feedSearch.oninput=renderAll;els.category.onchange=renderAll;els.source.onchange=renderAll;els.sort.onchange=renderAll;els.sidebarToggle.onclick=()=>document.body.classList.toggle("sidebar-collapsed");els.mobileMenu.onclick=()=>{els.sidebar.classList.add("mobile-open");els.mobileBackdrop.hidden=false};els.mobileBackdrop.onclick=closeMobileNav;els.clearBookmarks.onclick=()=>{state.bookmarks.clear();localStorage.removeItem("cyberintel.bookmarks");renderAll()};document.querySelectorAll(".nav-item[data-category]").forEach(n=>n.onclick=e=>{e.preventDefault();els.category.value=n.dataset.category;showSection("latest");renderAll();history.replaceState(null,"","#latest")});document.addEventListener("keydown",e=>{if(e.key==="/"&&document.activeElement!==els.search&&document.activeElement!==els.feedSearch){e.preventDefault();els.search.focus()}if(e.key==="Escape"){els.search.value="";els.feedSearch.value="";renderAll()}})}
function init(){renderSources();bindEvents();route();loadNews()}
init();
